Add support for Ed25519 sign and verify
konovod/monocypher.cr pull request #2
Opened 2020-04-22 17:55 UTC by kingsleyh

This PR adds:

1. Ed25519PublicSigningKey
2. Ed25519Signature

To allow signing and verification using the more widely used Ed25519 + SHA512 variant. 

I required this for my http://sushichain.io to allow compatibility with existing javascript ed25519 libraries for the sushichain crypto wallet

2020-04-23 17:13 UTC, kingsleyh commented
I may not need this now - as I'm thinking of generating a javascript version of monocypher using emscripten which means I don't have to worry about compatibility with existing javascript libs

2020-04-24 15:42 UTC, kingsleyh commented
Actually I am after all going to need this as the emscripten route is not as nice as the existing js libs - which I've now got working with monocypher.

2020-09-15 07:39 UTC, kingsleyh commented
In my branch I'm upgrading monocypher to the latest version.

2021-06-01 11:27 UTC, konovod requested changes
LGTM otherwise

2021-06-01 11:27 UTC, konovod commented on README.md
> +
Should be rephrased to be merged in, well, original repo.

2021-06-01 11:27 UTC, konovod commented on README.md
> +    github: axentro/monocypher
same here.

2021-06-01 11:28 UTC, konovod commented
wow, i'm impressed to see this library used in production. Please modify the readme if you want to merge the PR.

2021-06-01 11:31 UTC, kingsleyh commented
Wow got a reply after more than 1 year hahahh! I'll change the readme so you can merge it

2021-06-01 11:56 UTC, merged